# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Blog"
  url = "/"
  weight = 10

[[main]]
  name = "Ãœber mich"
  url = "about"
  weight = 20

[[main]]
  name = "Projekte"
  url = "my-projects"
  weight = 30

[[main]]
  name = "Erfahrung"
  url = "experience"
  weight = 40

[[main]]
  name = "Kontakt"
  url = "contact"
  weight = 80

# [[main]]
#   name = "Impressum"
#   url = "de/impressum"
#   weight = 40


# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Kubernetes in Production"
#   url = "project/notes-about-kubernetes-in-production"
#   weight = 40

# [[main]]
  # name = "Publications"
  # url = "#featured"
  # weight = 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
  #  weight = 150
